# Generated by Django 2.0.4 on 2019-01-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timesstamp'], 'verbose_name': 'Blog Entry', 'verbose_name_plural': 'Blog Entry'},
        ),
    ]
